release:
  title-prefix: "v"
  initial-version: "0.0.1"
  tag-prefix: "v"
branch:
  version-branch-prefix: "v"
  bump-version-commit-prefix: "v"
categories:
  - title: "Breaking Changes!"
    labels:
      - "BreakingChange"
    commits:
      - "breaking:"
    changes-prefix: ":warning: "
  - title: "Changes"
    labels:
      - "Feature"
    commits:
      - "feature:"
    changes-prefix: ":gift: "
  - title: "Changes"
    labels:
      - Maintenance
    commits:
      - "change:"
    changes-prefix: ":hammer: "
  - title: "Bug Fixes"
    labels:
      - "Bug"
    commits:
      - "fix:"
    changes-prefix: ":ambulance: "
  - title: "Changes"
    labels:
      - "Documentation"
    commits:
      - "document:"
    changes-prefix: ":blue_book: "
  - title: "Dependency Updates"
    labels:
      - "Dependencies"
    skip-label: "Development"
    commits:
      - "dependency:"
    changes-prefix: ":green_book: "
bump:
  default: "patch"
  major:
    labels:
      - "BreakingChange"
    commits:
      - "breaking:"
  minor:
    labels:
      - "Feature"
    commits:
      - "feature:"
files:
  - file-path: "version.py"
    line: 1
